# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu/jammy64"
    config.vm.hostname = "Pr1Gr5"
    config.vm.network "private_network", ip: "192.168.5.5"
    config.vm.provision "shell", path: "script.sh"
    config.vm.provider "virtualbox" do |vb|
	    vb.name = "Pr1Gr5"
      vb.memory = "1024"
      vb.cpus = 2
    end
end
